<?php

namespace MIKA\PlatformBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFacture($user)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.user = :user')
            ->andWhere('u.validate = 1')
            ->orderBy('u.id')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }
}
